V0.1
hyperlinkgroup/roadkit-sdk-ios pull request #1
Opened 2023-02-10 08:46 UTC by kaevinio

Aktuell greift der SDK noch auf Roadkit Dev in Firebase zu, weil die Cloud Functions live noch nicht deployed sind.

2023-02-22 11:55 UTC, annanna requested changes

2023-02-22 11:55 UTC, annanna commented on Roadkit/Sources/Roadkit/API/Routes.swift
> +    var userID = ""
warum gibt es hier einen Standardwert? Die sollte ja nie leer sein, oder?

2023-02-22 11:55 UTC, annanna commented on Roadkit/Sources/Roadkit/API/Routes.swift
> +    private let host = "https://europe-west3-roadkit-dev-swift.cloudfunctions.net/topics/"
das zeigt noch auf Dev

2023-02-22 11:55 UTC, annanna commented on Roadkit/Sources/Roadkit/Enums/HTTP/HTTPMethod.swift
> +    case get = "GET",
könntest hier auch mit `rawValue.uppercased` arbeiten

2023-02-22 11:55 UTC, annanna commented on Roadkit/Package.swift
> +// swift-tools-version: 5.5
ganz grundsätzlich ist hier alles eine Ebene zu hoch, also das `Package.swift`-File muss direkt in die Root, sonst kannst du es nicht über XCode hinzufügen

2023-02-22 11:55 UTC, annanna commented on Roadkit/Sources/Roadkit/RoadkitManager.swift
> +    public func setupRoadkit(projectID: String, userID: String) {
Mh ja, die ist ja eigentlich nicht optional, oder? Also den Rest kann man ja nicht nutzen, wenn die `projectId` und userId leer sind?
Könnten es entweder wie bei Firebase machen, dass mit Absicht Crashes geworfen werden, wenn man vorher nicht `configure()` aufgerufen hat. Oder wir nehmen einfach ein init 😬

2023-02-22 11:55 UTC, annanna commented on Roadkit/Sources/Roadkit/API/NetworkResponse.swift
> +//  File.swift
filename

2023-02-22 11:55 UTC, annanna commented on Roadkit/Sources/Roadkit/API/Routes.swift
> +    private let host = "https://europe-west3-roadkit-dev-swift.cloudfunctions.net/topics/"
(hast du geschrieben, ich weiß, aber die Cloud Functions sind ja approved)

2023-02-28 08:04 UTC, kaevinio commented on Roadkit/Sources/Roadkit/API/Routes.swift
> +    var userID = ""
Jain, du hast Recht, ich die UserID nicht mehr optional aber projectID und topicID werden nicht bei beiden gebraucht

2023-02-28 08:11 UTC, kaevinio commented on Roadkit/Sources/Roadkit/RoadkitManager.swift
> +    public func setupRoadkit(projectID: String, userID: String) {
Also die UserID kann leer sein (wenn man sich in einer App nicht anmelden muss) aber für die ProjectID wird jetzt gechecked und ansonsten crasht es.

2023-02-28 11:06 UTC, annanna approved these changes

2023-02-28 11:06 UTC, merged