ROK-50: Voting for empty userID
hyperlinkgroup/roadkit-sdk-ios pull request #11
Opened 2023-04-24 07:17 UTC by kaevinio

- Set anonymous setup method
- Create UUID for anonymous user and save to user defaults
- Throw error if setup method is with userID but no ID is given

2023-04-25 07:36 UTC, annanna requested changes

2023-04-25 07:36 UTC, annanna commented on .github/README.md
> +To setup RoadKit, you need to initialize the SDK with your project's ID, declare the setup method and (optionally) provide a UserID. The ProjectID can be found in your app under the info tab of the r
wie bei PLB schon angemerkt, wär es sicher für die User interessant zu wissen was passiert wenn man mit einer Methode initialisiert und dann wechselt im Verlauf der App

2023-04-25 07:36 UTC, annanna commented on .github/README.md
> +To setup RoadKit, you need to initialize the SDK with your project's ID, declare the setup method and (optionally) provide a UserID. The ProjectID can be found in your app under the info tab of the r
Ok. ich versteh schon, dass so oder so ne UserId gesetzt wird und die natürlich später überschrieben werden kann. Aber ich kann dann quasi nicht zurückwechseln, ja? Also wenn ich erst jemanden mit `userId` hab und der sich ausloggt und ggf die App anonym weiter nutzt (wie bei PB)?

Ich würde auf jeden Fall als User total davon ausgehen, dass der Modus in dem ich das Setup für RoadKit durchführe bleibt. Man könnte das auch so weiter suggerieren und entsprechende Funktionen zum Wechseln des Modus anbieten (also `updateSetupMethod` oder so und dann wird entweder `updateUserID` aufgerufen mit der neuen UserID oder anonym gesetzt und eine generiert?)


Ist es für User eigentlich relevant in der RoadKit-App zu sehen, ob das ein anonymisierte User war oder nicht?

2023-04-26 07:35 UTC, annanna commented
- setup-Funktion bleibt so
- dazu Funktionen zum Wechseln vom Modus + Doku
- extra Ticket zum Speichern vom Modus

2023-05-02 06:13 UTC, annanna commented
Ticket zum Speichern vom Modus erstellt: [ROK-93](https://linear.app/hyperlinkgroup/issue/ROK-93/setupmode-im-topic-speichern)

2023-05-02 06:19 UTC, annanna approved these changes

2023-05-02 09:59 UTC, HeikoRothermel approved these changes

2023-05-05 07:31 UTC, merged