Rok 102 roadmap laden aller offenen topics
hyperlinkgroup/roadkit-sdk-ios pull request #17
Opened 2023-06-09 05:48 UTC by HeikoRothermel

In der RoadMapView werden nun auch die improvements geladen und entsprechend des Titels soriert.

2023-06-12 10:42 UTC, annanna requested changes
Feedback kommt noch nicht mit. Hattest du dich da aktiv dagegen entschieden? Würde das mit reinnehmen zu den Funktionen, weil man es ja auch veröffentlichen kann.

Vielleicht bereden wir das mit der Segmented Control auch noch mal mit Katya ob sie da Ideen hat, weil's schon ein bisschen komisch ist, dass Funktionen/Verbesserungen/Feedback zusammen unter dem Begriff Funktionen fallen würde, hab aber selber keine gute Idee wie wir das sonst darstellen.

2023-06-12 10:59 UTC, HeikoRothermel commented
Ich bin bislang davon ausgegangen, dass das offene Feedback dann umgewandelt wird in Improvements/Features/Bugs. Aber du hast vollkommen recht, dass es ja vielleicht auch angezeigt werden soll. Ich finde es eine gute Idee da mal bei Katya anzufragen. Ich mach mal einen Post in den RoadKit-Channel und weise dann Katya ein Design-Ticket zu. So war es ja gewünscht und Patrick hatte letzte Woche ja sowieso schon Mal nachgefragt, ob wir noch Aufgaben für Katya haben.

2023-06-12 17:29 UTC, annanna commented
Ok, dann würd ich sagen du kannst fürs Erste hier noch das Feedback mit laden?
Und dann kann das schon mal gemergt werden und wir warten auf ein neues Design

2023-06-16 09:00 UTC, annanna approved these changes

2023-06-16 13:01 UTC, merged